import Foundation
import Security

enum KeychainManager {
    private static let service = "com.reader.ReaderApp"
    
    static func save(key: String, value: String) {
        guard let data = value.data(using: .utf8) else { return }
        
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: key
        ]
        
        // Delete existing item first
        SecItemDelete(query as CFDictionary)
        
        // Add new item
        var newQuery = query
        newQuery[kSecValueData as String] = data
        
        SecItemAdd(newQuery as CFDictionary, nil)
    }
    
    static func get(key: String) -> String? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: key,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne
        ]
        
        var result: AnyObject?
        let status = SecItemCopyMatching(query as CFDictionary, &result)
        
        guard status == errSecSuccess,
              let data = result as? Data,
              let string = String(data: data, encoding: .utf8) else {
            return nil
        }
        
        return string
    }
    
    static func delete(key: String) {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: key
        ]
        
        SecItemDelete(query as CFDictionary)
    }
    
    // Convenience methods for provider API keys
    static func getKey(for provider: ProviderType) -> String? {
        // First check Keychain (user-entered keys)
        if let key = get(key: "apiKey_\(provider.rawValue)"), !key.isEmpty {
            return key
        }
        // Fall back to bundled secrets if available
        return bundledKey(for: provider)
    }

    private static func bundledKey(for provider: ProviderType) -> String? {
        // Secrets.swift is auto-generated by scripts/setup-secrets.sh
        // and contains keys from the root .env file.
        // If Secrets.swift doesn't exist, this returns nil.
        #if SECRETS_AVAILABLE
        let key: String? = {
            switch provider {
            case .claude: return Secrets.claudeAPIKey
            case .openai: return Secrets.openAIAPIKey
            case .gemini: return Secrets.geminiAPIKey
            }
        }()
        if let key = key, !key.isEmpty { return key }
        #endif
        return nil
    }
    
    static func setKey(_ apiKey: String, for provider: ProviderType) {
        save(key: "apiKey_\(provider.rawValue)", value: apiKey)
    }
    
    static func deleteKey(for provider: ProviderType) {
        delete(key: "apiKey_\(provider.rawValue)")
    }
}
