#!/bin/bash
# Setup script to deploy secrets from .env to various targets

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "Error: .env file not found at $ENV_FILE"
    echo "Copy .env.example to .env and fill in your API keys"
    exit 1
fi

# Load .env file
set -a
source "$ENV_FILE"
set +a

usage() {
    echo "Usage: $0 <target>"
    echo ""
    echo "Targets:"
    echo "  worker     - Deploy secrets to Cloudflare Worker"
    echo "  ios        - Generate iOS configuration file"
    echo "  all        - Setup all targets"
    echo ""
}

setup_worker() {
    echo "Setting up Cloudflare Worker secrets..."
    cd "$ROOT_DIR/worker"

    if [ -n "$CLAUDE_API_KEY" ]; then
        echo "$CLAUDE_API_KEY" | wrangler secret put CLAUDE_API_KEY
    fi

    if [ -n "$OPENAI_API_KEY" ]; then
        echo "$OPENAI_API_KEY" | wrangler secret put OPENAI_API_KEY
    fi

    if [ -n "$GEMINI_API_KEY" ]; then
        echo "$GEMINI_API_KEY" | wrangler secret put GEMINI_API_KEY
    fi

    echo "Worker secrets configured!"
}

setup_ios() {
    echo "Generating iOS secrets configuration..."

    IOS_SECRETS_FILE="$ROOT_DIR/ios/ReaderApp/Secrets.swift"

    cat > "$IOS_SECRETS_FILE" << SWIFT
// Auto-generated file - DO NOT COMMIT
// Generated by scripts/setup-secrets.sh

import Foundation

enum Secrets {
    static let claudeAPIKey = "$CLAUDE_API_KEY"
    static let openAIAPIKey = "$OPENAI_API_KEY"
    static let geminiAPIKey = "$GEMINI_API_KEY"
}
SWIFT

    echo "Generated $IOS_SECRETS_FILE"
    echo ""
    echo "IMPORTANT: In Xcode, add SECRETS_AVAILABLE to Swift Compiler - Custom Flags:"
    echo "  1. Select ReaderApp target"
    echo "  2. Build Settings > Swift Compiler - Custom Flags > Active Compilation Conditions"
    echo "  3. Add: SECRETS_AVAILABLE"
    echo ""
    echo "Also add Secrets.swift to your Xcode project if not already added."
}

case "${1:-}" in
    worker)
        setup_worker
        ;;
    ios)
        setup_ios
        ;;
    all)
        setup_worker
        setup_ios
        ;;
    *)
        usage
        exit 1
        ;;
esac
