#!/bin/bash
# Setup script to deploy secrets from .env to various targets

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "Error: .env file not found at $ENV_FILE"
    echo "Copy .env.example to .env and fill in your API keys"
    exit 1
fi

# Load .env file
set -a
source "$ENV_FILE"
set +a

usage() {
    echo "Usage: $0 <target>"
    echo ""
    echo "Targets:"
    echo "  worker     - Deploy secrets to Cloudflare Worker (production)"
    echo "  worker-dev - Generate .dev.vars for local worker development"
    echo "  ios        - Generate iOS configuration file"
    echo "  all        - Setup all targets"
    echo ""
}

setup_worker() {
    echo "Setting up Cloudflare Worker secrets..."
    cd "$ROOT_DIR/worker"

    if [ -n "$CLAUDE_API_KEY" ]; then
        echo "$CLAUDE_API_KEY" | wrangler secret put CLAUDE_API_KEY
    fi

    if [ -n "$OPENAI_API_KEY" ]; then
        echo "$OPENAI_API_KEY" | wrangler secret put OPENAI_API_KEY
    fi

    if [ -n "$GEMINI_API_KEY" ]; then
        echo "$GEMINI_API_KEY" | wrangler secret put GEMINI_API_KEY
    fi

    if [ -n "$BRAVE_SEARCH_API_KEY" ]; then
        echo "$BRAVE_SEARCH_API_KEY" | wrangler secret put BRAVE_SEARCH_API_KEY
    fi

    if [ -n "$WORKER_API_KEY" ]; then
        echo "$WORKER_API_KEY" | wrangler secret put WORKER_API_KEY
    fi

    echo "Worker secrets configured!"
}

setup_worker_dev() {
    echo "Generating .dev.vars for local worker development..."

    DEV_VARS_FILE="$ROOT_DIR/worker/.dev.vars"

    cat > "$DEV_VARS_FILE" << VARS
# Auto-generated file - DO NOT COMMIT
# Generated by scripts/setup-secrets.sh

CLAUDE_API_KEY=$CLAUDE_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY
GEMINI_API_KEY=$GEMINI_API_KEY
BRAVE_SEARCH_API_KEY=$BRAVE_SEARCH_API_KEY
WORKER_API_KEY=$WORKER_API_KEY
VARS

    echo "Generated $DEV_VARS_FILE"
}

setup_ios() {
    echo "Generating iOS secrets configuration..."

    IOS_SECRETS_FILE="$ROOT_DIR/ios/ReaderApp/Secrets.swift"

    cat > "$IOS_SECRETS_FILE" << SWIFT
// Auto-generated file - DO NOT COMMIT
// Generated by scripts/setup-secrets.sh

import Foundation

enum Secrets {
    static let workerAPIKey = "$WORKER_API_KEY"
}
SWIFT

    echo "Generated $IOS_SECRETS_FILE"
    echo ""
    echo "IMPORTANT: In Xcode, add SECRETS_AVAILABLE to Swift Compiler - Custom Flags:"
    echo "  1. Select ReaderApp target"
    echo "  2. Build Settings > Swift Compiler - Custom Flags > Active Compilation Conditions"
    echo "  3. Add: SECRETS_AVAILABLE"
    echo ""
    echo "Also add Secrets.swift to your Xcode project if not already added."
}

case "${1:-}" in
    worker)
        setup_worker
        ;;
    worker-dev)
        setup_worker_dev
        ;;
    ios)
        setup_ios
        ;;
    all)
        setup_worker
        setup_worker_dev
        setup_ios
        ;;
    *)
        usage
        exit 1
        ;;
esac
